### ISSUE TITLE
Error - Keeps restarting

### ISSUE THREAD

**Issue by sean89503** [lynxaegon/obsidian-anysocket-sync#5]
log has error
`SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Storage.readMetadata (/app/libs/fs/Storage.js:50:25)
    at async Server.onFileEvent (/app/libs/server.js:180:26)
Node.js v19.9.0`

**Comment by sean89503** [comment]
I think it was due to having a emoji in a folder name I had 🔁
